# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-18 17:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('musilux', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='song',
            name='last_accessed',
            field=models.DateField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='song',
            name='midifile',
            field=models.FileField(upload_to='midifiles/'),
        ),
        migrations.AlterField(
            model_name='song',
            name='year_c',
            field=models.CharField(help_text='Year composed', max_length=4),
        ),
    ]
